In [1]:
import pandas as pd

**OECD BIMTS 4 digit HS code level bulk data comes in two files spliting on the time period. Here I am considering 1995 to 2024. Cleaning and preparing of the data take the following steps:**  
   > - a. Renaming the exporter and importer columns
   > - b. Removing self loops and duplicate rows and keeping the first instance only
   > - c. Counting hysteresis column for all dataframes
   > - d. Sorting values by country pair and time period
   > - e. Reseting index
>    - Aggregating the unique and reproducible cultural goods data on country pair and time, while tracking the HS codes and number of products traded among each pair in a particular year in the column 'PRODUCT_HS' and 'product_count'
>     - So this notebook will three different csv files in the 'cleaned' subfolder of the folder 'data', for unique and reproducible cultural goods, and non-cultural goods data.

In [2]:
# Started: 12:13AM, Ended: 12:18AM
oecd = []
dtype_dict = {"REF_AREA": "category","COUNTERPART_AREA": "category","PRODUCT_HS": "category","ADJUSTMENT": "category", "TIME_PERIOD": "int16","OBS_VALUE": "float32"}
cols = ["REF_AREA","COUNTERPART_AREA","PRODUCT_HS","TIME_PERIOD","OBS_VALUE", "ADJUSTMENT"]

for year in range(1995, 2025):
    file = f'../data/raw/HS17_4D_DE_Bulk_{year}.csv'
    df = pd.read_csv(file, sep='|', usecols = cols, dtype = dtype_dict)
    df["year_file"] = year
    oecd.append(df)
t = pd.concat(oecd, ignore_index=True)

In [3]:
t.head()

,REF_AREA,COUNTERPART_AREA,PRODUCT_HS,TIME_PERIOD,OBS_VALUE,ADJUSTMENT,year_file
0,BEL_LUX,PHL,HS17_6309,1995,0.029524,B,1995
1,BEL_LUX,PHL,HS17_6309,1995,0.029524,B_ADJ_RX,1995
2,W,GHA,HS17_6504,1995,0.016462,B_ADJ_RX,1995
3,W,ZWE,HS17_3602,1995,5.386201,B,1995
4,HRV,NOR,HS17_7606,1995,1.241157,B_ADJ_RX,1995

In [4]:
t['PRODUCT_HS'].nunique()

1224

In [5]:
t['TIME_PERIOD'].nunique()

30

In [6]:
t['TIME_PERIOD'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024], dtype=int16)

In [7]:
t.shape

(275120328, 7)

In [8]:
t = t[t['ADJUSTMENT'] == 'B_ADJ_RX']
t = t.rename(columns = {'REF_AREA': 'iso_o'})
t = t.rename(columns = {'COUNTERPART_AREA': 'iso_d'})
t = t[t['iso_o'] != t['iso_d']]

In [9]:
t.shape

(137281906, 7)

In [10]:
print(t['iso_o'].nunique())
print(t['iso_d'].nunique())
print(t['TIME_PERIOD'].nunique())
print(t['PRODUCT_HS'].nunique())
print(t.groupby(['iso_o', 'iso_d']).ngroups)

205
205
30
1224
39525

In [11]:
t = t[t['iso_o'] != 'W']
t = t[t['iso_d'] != 'W']

In [12]:
print(t.groupby(['iso_o', 'iso_d']).ngroups)

39117

In [13]:
t['iso_o'].unique()

array(['BEL_LUX', 'HRV', 'IND', 'ISR', 'NLD', 'WSM', 'ITA', 'SACU', 'HTI',
       'HUN', 'BLZ', 'BMU', 'BOL', 'IRL', 'BRA', 'IDN', 'YEM', 'ZMB',
       'ZWE', 'ABW', 'AFG', 'AGO', 'ALB', 'IRN', 'AND', 'NOR', 'ARE',
       'BRB', 'BRN', 'ISL', 'CAF', 'CAN', 'ARG', 'NPL', 'NRU', 'NZL',
       'ARM', 'ATG', 'AUS', 'OMN', 'JAM', 'PAK', 'JOR', 'CHE', 'PAN',
       'JPN', 'PER', 'PHL', 'AUT', 'IRQ', 'PLW', 'PNG', 'POL', 'CHL',
       'PRK', 'PRT', 'CHN', 'KAZ', 'AZE', 'BEN', 'KEN', 'BFA', 'BGD',
       'BGR', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR', 'PRY', 'PYF', 'QAT',
       'ROU', 'BHR', 'WXD', 'BHS', 'BIH', 'BLR', 'RUS', 'BDI', 'CIV',
       'KWT', 'CMR', 'COD', 'LAO', 'COG', 'COL', 'LBN', 'RWA', 'SAU',
       'COM', 'CPV', 'CRI', 'SCG_F', 'LBR', 'LBY', 'LCA', 'CUB', 'SDN_F',
       'SEN', 'LKA', 'SGP', 'CYP', 'CZE', 'LTU', 'LVA', 'MAC', 'MAR',
       'SLB', 'SLE', 'DEU', 'MDA', 'SLV', 'MDG', 'STP', 'SUR', 'SVK',
       'MDV', 'MEX', 'SVN', 'MHL', 'MKD', 'BTN', 'MLI', 'SWE', 'MLT',
       'MMR', 'MNG', 'MOZ', 'MRT', 'MSR', 'MUS', 'MWI', 'MYS', 'NCL',
       'NER', 'SYC', 'SYR', 'NGA', 'NIC', 'TGO', 'THA', 'DJI', 'DMA',
       'DNK', 'TKM', 'TON', 'TTO', 'TUN', 'TUR', 'DOM', 'DZA', 'ECU',
       'EGY', 'ERI', 'ESP', 'TUV', 'TWN', 'EST', 'TZA', 'UGA', 'UKR',
       'ETH', 'FIN', 'URY', 'USA', 'FJI', 'FRA', 'GAB', 'GBR', 'UZB',
       'VCT', 'VEN', 'VNM', 'VUT', 'GEO', 'GHA', 'GIN', 'GMB', 'GRC',
       'GRD', 'GRL', 'GTM', 'GUY', 'HKG', 'TCD', 'HND', 'TJK', 'FSM',
       'GNB', 'GNQ', 'BEL', 'LUX', 'PSE', 'ZAF', 'SWZ', 'BWA', 'LSO',
       'NAM', 'TLS', 'MNE', 'SRB', 'SDN', 'SSD'], dtype=object)

In [14]:
t_dupli = t.duplicated(keep = 'last')
t_unique = t[~t_dupli ]

In [15]:
t_unique.shape

(125538245, 7)

In [16]:
t_unique['PRODUCT_HS'].nunique()

1224

In [17]:
t_unique['PRODUCT_HS'].unique()

array(['HS17_6309', 'HS17_7606', 'HS17_2008', ..., 'HS17_3803',
       'HS17_2612', 'HS17_7109'], dtype=object)

In [18]:
unique_codes = ['HS17_9701','HS17_9702','HS17_9703','HS17_9706']
reproducible_codes = ['HS17_4901','HS17_4902','HS17_4904','HS17_3706', 'HS17_8523']

In [19]:
unique = t_unique[t_unique['PRODUCT_HS'].isin(unique_codes)]
reproducible = t_unique[t_unique['PRODUCT_HS'].isin(reproducible_codes)]
total = t_unique[t_unique['PRODUCT_HS'] == '_T']

In [20]:
alt_total = t_unique[~t_unique['PRODUCT_HS'].isin(unique_codes)]
alt_total = alt_total[~alt_total['PRODUCT_HS'].isin(reproducible_codes)]
alt_total = alt_total[alt_total['PRODUCT_HS'] != '_T']

In [21]:
len(set(t_unique['PRODUCT_HS'].unique()) - set(alt_total['PRODUCT_HS'].unique()))

10

In [22]:
alt_total = alt_total.groupby(['iso_o', 'iso_d', 'TIME_PERIOD']).agg({'OBS_VALUE': 'sum', 'PRODUCT_HS': lambda x :tuple(sorted(set(x)))}).reset_index()

In [23]:
alt_total['product_count'] = alt_total['PRODUCT_HS'].apply(len)

In [24]:
alt_total

,iso_o,iso_d,TIME_PERIOD,OBS_VALUE,PRODUCT_HS,product_count
0,ABW,AFG,2017,0.069146,"(HS17_1605, HS17_2704, HS17_3006, HS17_4202, H...",10
1,ABW,AFG,2018,0.422331,"(HS17_0406, HS17_1604, HS17_1806, HS17_1905, H...",15
2,ABW,AFG,2019,0.278743,"(HS17_0405, HS17_0406, HS17_0409, HS17_0410, H...",29
3,ABW,AGO,2005,0.002650,"(HS17_8215, HS17_8711)",2
4,ABW,AGO,2006,0.069866,"(HS17_3919, HS17_8201, HS17_8205, HS17_8703, H...",5
...,...,...,...,...,...,...
837884,ZWE,ZMB,2020,58.510490,"(HS17_0101, HS17_0102, HS17_0106, HS17_0301, H...",336
837885,ZWE,ZMB,2021,74.577728,"(HS17_0101, HS17_0105, HS17_0106, HS17_0210, H...",351
837886,ZWE,ZMB,2022,89.190079,"(HS17_0101, HS17_0106, HS17_0301, HS17_0303, H...",350
837887,ZWE,ZMB,2023,97.020058,"(HS17_0101, HS17_0102, HS17_0106, HS17_0301, H...",376
837888,ZWE,ZMB,2024,114.249893,"(HS17_0101, HS17_0102, HS17_0106, HS17_0301, H...",354

In [25]:
# unique = unique.drop(columns = ['ADJUSTMENT', 'year_file'])
# reproducible = reproducible.drop(columns = ['ADJUSTMENT', 'year_file'])
# total = total.drop(columns = ['ADJUSTMENT', 'year_file'])
# alt_total = alt_total.drop(columns = ['ADJUSTMENT', 'year_file'])

In [26]:
unique = unique.groupby(['iso_o', 'iso_d', 'TIME_PERIOD']).agg({'OBS_VALUE': 'sum', 'PRODUCT_HS': lambda x :tuple(sorted(set(x)))}).reset_index()

In [27]:
unique['product_count'] = unique['PRODUCT_HS'].apply(len)

In [28]:
reproducible = reproducible.groupby(['iso_o', 'iso_d', 'TIME_PERIOD']).agg({'OBS_VALUE': 'sum', 'PRODUCT_HS': lambda x :tuple(sorted(set(x)))}).reset_index()

In [29]:
reproducible['product_count'] = reproducible['PRODUCT_HS'].apply(len)

In [30]:
total = total.rename(columns = {'OBS_VALUE': 'total'})
reproducible = reproducible.rename(columns = {'OBS_VALUE': 'reproducible'})
unique = unique.rename(columns = {'OBS_VALUE': 'unique'})
alt_total = alt_total.rename(columns = {'OBS_VALUE': 'total'})

In [31]:
t = total.merge(unique, on = ['iso_o', 'iso_d', 'TIME_PERIOD'], how='left').merge(reproducible, on = ['iso_o', 'iso_d', 'TIME_PERIOD'], how='left')

In [32]:
t[['unique', 'reproducible', 'total']] = (t[['unique', 'reproducible', 'total']].fillna(0))

In [33]:
t['noncultural_trade'] = (t['total'] - t['unique']- t['reproducible'])

In [34]:
#alt_total[(alt_total['iso_o'] == 'SACU') & (alt_total['iso_d'] == 'DOM')]

In [35]:
#t[(t['iso_o'] == 'SACU') & (t['iso_d'] == 'DOM')]

In both way the non-cultural product values are exactly same. So, I am using 'alt_total' dataframe.

In [36]:
alt_total = alt_total.rename(columns = {'total':'noncultural_trade'})

In [37]:
alt_total = alt_total.reset_index(drop = True)
unique = unique.reset_index(drop = True)
reproducible = reproducible.reset_index(drop = True)

In [38]:
memory = 0.3
def compute_hysteresis(series):
    '''It takes a numeric panda series, initializes an empty list to store the hysteresis values, and two values for 
    previous year's trade volume and cummulative trade volume. Then it counts the husteresis value for a particular year and 
    appends it to the list of hysteresis values.'''
    hyst = []
    prev_cum = 0
    prev_val = 0
    for val in series:
        hyst_val = memory * prev_cum + prev_val
        hyst.append(hyst_val)
        prev_cum = hyst_val
        prev_val = val
    return hyst

In [39]:
unique['hysteresis_unique'] = (unique.groupby(['iso_o', 'iso_d'])['unique'].transform(compute_hysteresis))

In [40]:
reproducible['hysteresis_reproducible'] = (reproducible.groupby(['iso_o', 'iso_d'])['reproducible'].transform(compute_hysteresis))

In [41]:
alt_total['hysteresis_noncultural_trade'] = (alt_total.groupby(['iso_o', 'iso_d'])['noncultural_trade'].transform(compute_hysteresis))

In [42]:
alt_total = alt_total.drop(columns = 'PRODUCT_HS')
unique = unique.drop(columns = 'PRODUCT_HS')
reproducible = reproducible.drop(columns = 'PRODUCT_HS')

In [43]:
print(alt_total['iso_o'].nunique())
print(alt_total['iso_d'].nunique())

204
204

In [44]:
print(unique['iso_o'].nunique())
print(unique['iso_d'].nunique())

204
204

In [45]:
print(reproducible['iso_o'].nunique())
print(reproducible['iso_d'].nunique())

204
204

In [46]:
unique = unique.sort_values(['iso_o', 'iso_d', 'TIME_PERIOD'])
reproducible = reproducible.sort_values(['iso_o', 'iso_d', 'TIME_PERIOD'])
alt_total = alt_total.sort_values(['iso_o', 'iso_d', 'TIME_PERIOD'])

In [47]:
alt_total.head(2)

,iso_o,iso_d,TIME_PERIOD,noncultural_trade,product_count,hysteresis_noncultural_trade
0,ABW,AFG,2017,0.069146,10,0.000000
1,ABW,AFG,2018,0.422331,15,0.069146

In [48]:
assert unique['iso_o'].nunique() == reproducible['iso_o'].nunique() == alt_total['iso_o'].nunique()

In [49]:
assert unique['iso_d'].nunique() == reproducible['iso_d'].nunique() == alt_total['iso_d'].nunique()

In [50]:
unique.to_csv("../data/cleaned/unique.csv", encoding = 'utf-8', index = False)
reproducible.to_csv("../data/cleaned/reproducible.csv", encoding = 'utf-8', index = False)
alt_total.to_csv("../data/cleaned/noncultural.csv", encoding = 'utf-8', index = False)