In [114]:
import pandas as pd
import numpy as np

*Time variant indicators are downloaded from WDI for each period. I extracted the zip files with raw data in the 'raw' subfolder of the 'data' folder. Without changing the names of the raw data file, I just added the `year name` at the tail of the original name extracted from WDI, so that I can keep track. Example: `dc261827-d380-414a-b6ff-55a77579a878_Data.csv` was the name for the data for 2000. I changed the name like `dc261827-d380-414a-b6ff-55a77579a878_Data2000.csv`.*

**Preparing the time variant data takes the following steps:**
>1. Pruning the unnecessary rows with formulas from the tail of the data
>2. Renaming the columns
>3. Replacing the '..' values with NaN
>4. Converting all columns to numeric from object type except the 'iso_o' and 'country'
>5. Finding the mean of the variables of that year and imputing that to missing rows
>6. Creating a column with log transformed GDP value of that year
>7. Finding the common countries those are present in the trade data and also in this time variant data
>8. Only keeping the common countries for each year.
>9. Saving the cleaned data as a csv file named like `attributeYEAR.csv`
>10. Finally concatenating all the dataframes on columns and sorting those with country and year for gravity analysis
>11. Saving the concataned data as `attribute2000_2023.csv` in the cleaned folder

In [115]:
gdp_pc = pd.read_csv("../data/raw/29054d80-49f3-4277-bf38-57f7a9c4f72e_Series - Metadata.csv", encoding="latin1")
trade_ratio = pd.read_csv("../data/raw/239ee599-034e-4f84-bc4a-c9a3606d2f27_Series - Metadata.csv", encoding="latin1")

In [116]:
total_trade= pd.read_csv("../data/cleaned/total_edgelist.csv")

In [117]:
m = set(gdp_pc['Country Code'].unique()) & set(total_trade['iso_o'].unique())
print(len(m))
print(set(total_trade['iso_o'].unique()) - set(gdp_pc['Country Code'].unique()))

190
{'MSR', 'TWN'}

In [118]:
gdp_pc.columns = [col if not col.startswith("19") and not col.startswith("20") else col.split()[0] for col in gdp_pc.columns]

In [119]:
trade_ratio.columns = [col if not col.startswith("19") and not col.startswith("20") else col.split()[0] for col in trade_ratio.columns]

In [120]:
rename_columns = {'Country Code': 'iso_o', 'Country Name': 'country'}
years = list(map(str, range(1995, 2025)))

In [121]:
gdp_pc = gdp_pc.rename(columns = rename_columns).iloc[:265, :]
gdp_pc = gdp_pc.rename(columns = {'Series Name': 'gdp_pc'})
gdp_pc = gdp_pc.drop(columns = 'Series Code')
gdp_pc[years] = gdp_pc[years].replace('..', np.nan)
gdp_pc[years] = gdp_pc[years].apply(lambda x: pd.to_numeric(x, errors='coerce')).round(2) 
gdp_pc[years] = gdp_pc[years].apply(lambda x: x.fillna(x.mean()))
gdp_pc = gdp_pc[gdp_pc['iso_o'].isin(m)]
gdp_pc = gdp_pc.reset_index(drop = True)

In [122]:
#gdp_pc.dtypes

In [123]:
#gdp_pc.isna().sum()

In [124]:
trade_ratio.head(2)

,Series Name,Series Code,Country Name,Country Code,1995,1996,1997,1998,1999,2000,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Trade (% of GDP),NE.TRD.GNFS.ZS,Afghanistan,AFG,..,..,..,..,..,..,...,..,..,..,..,..,46.7098945514103,51.4117163747271,72.8854696086536,67.5846651516385,..
1,Trade (% of GDP),NE.TRD.GNFS.ZS,Albania,ALB,40.1386989518314,44.4117820054663,44.7293780649181,47.1306266993222,49.8954184095195,61.6092610436407,...,71.2794476606014,74.0144504546815,76.7873817898989,75.6940783717425,75.382128932689,59.5206994391875,75.5904040905009,84.6980435944865,82.3524933990723,79.4546360752224

In [125]:
trade_ratio = trade_ratio.rename(columns = rename_columns).iloc[:265, :]
trade_ratio = trade_ratio.rename(columns={'Series Name': 'trade_ratio'})
trade_ratio = trade_ratio.drop(columns='Series Code')
trade_ratio[years] = trade_ratio[years].replace('..', np.nan)
trade_ratio[years] = trade_ratio[years].apply(lambda x: pd.to_numeric(x, errors='coerce')).round(2)
trade_ratio[years] = trade_ratio[years].apply(lambda x: x.fillna(x.mean()))
trade_ratio = trade_ratio[trade_ratio['iso_o'].isin(m)]
trade_ratio = trade_ratio.reset_index(drop=True)

In [126]:
total_trade['iso_o'].nunique()

192

In [127]:
trade_ratio.head(2)

,trade_ratio,country,iso_o,1995,1996,1997,1998,1999,2000,2001,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Trade (% of GDP),Afghanistan,AFG,69.623147,69.98665,71.556768,71.250505,71.133081,76.333532,75.541592,...,84.456267,82.486205,84.556978,86.73,85.642377,46.71,51.41,72.89,67.58,85.796119
1,Trade (% of GDP),Albania,ALB,40.140000,44.41000,44.730000,47.130000,49.900000,61.610000,64.250000,...,71.280000,74.010000,76.790000,75.69,75.380000,59.52,75.59,84.70,82.35,79.450000

In [128]:
trade_ratio = trade_ratio.rename(columns={"trade_ratio": "trade_ratio_value"})
long_trade = trade_ratio.melt(id_vars = ["country", "iso_o"], value_vars = years, var_name = "year", value_name = "trade_ratio")
long_trade = long_trade.sort_values(by=['country', 'iso_o', 'year'])

In [129]:
gdp_pc = gdp_pc.rename(columns={"gdp_pc": "gdp_pc_value"})
long_gdp_pc = gdp_pc.melt(id_vars = ["country", "iso_o"], value_vars = years, var_name = "year", value_name = "gdp_pc")
long_gdp_pc = long_gdp_pc.sort_values(by=['country', 'iso_o', 'year'])

In [130]:
# for year in range(1999, 2024):
#     globals()[f"at{year}"].to_csv(f"../data/cleaned/attribute{year}.csv", encoding = "utf-8", index = False)

### Preparing the RTA data

This dataset is collected from `https://www.ewf.uni-bayreuth.de/en/research/RTA-data/index.html`
### Steps:
1. keeping only the 'rta column and the years after 1999
2. checking for duplicates
3. removing self-loops
4. saving in the cleaned subfolder of the data folder

In [131]:
rta = pd.read_csv("../data/raw/rta_20241028.csv")

In [132]:
rta  = rta.rename(columns = {'exporter': 'iso_o'})
rta  = rta.rename(columns = {'importer': 'iso_d'})
rta = rta[rta['year'] >= 1995]

In [141]:
rta = rta[rta['iso_o'] != rta['iso_d']]

In [142]:
rta['iso_o'].nunique()

280

In [143]:
print(rta.groupby(['iso_o', 'iso_d']).ngroups)

78120

In [144]:
rta.shape[0]

2265480

In [145]:
rta.shape

(2265480, 4)

In [146]:
rta = rta[['iso_o', 'iso_d', 'year', 'rta']].reset_index(drop = True)

In [147]:
rta['year'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023], dtype=int64)

In [148]:
rta.head(2)

  iso_o iso_d  year  rta
0   ABW   AFG  1995    0
1   ABW   AFG  1996    0

In [149]:
rta.to_csv("../data/cleaned/rta_long.csv", encoding = 'utf-8', index = False)

In [150]:
rta_edgelist = rta.pivot_table(values = 'rta', index = ['iso_o', 'iso_d'], columns = 'year').reset_index()

In [151]:
rta_edgelist[(rta_edgelist['iso_o'] == 'BGD') & (rta_edgelist['iso_d'] == 'IND')] #sanity check

year,iso_o,iso_d,1995,1996,1997,1998,1999,2000,2001,2002,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
7370,BGD,IND,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [152]:
rta_edgelist.to_csv("../data/cleaned/rta_edgelist.csv", encoding = 'utf-8', index = False)

### Merging

In [153]:
long_gdp_pc.head(2)

         country iso_o  year        gdp_pc
0    Afghanistan   AFG  1995  15537.511489
190  Afghanistan   AFG  1996  15850.788000

In [154]:
wdi = long_gdp_pc.merge(long_trade, on = ['country','iso_o','year'], how = 'left').reset_index(drop= True)

In [155]:
wdi.head(2)

       country iso_o  year        gdp_pc  trade_ratio
0  Afghanistan   AFG  1995  15537.511489    69.623147
1  Afghanistan   AFG  1996  15850.788000    69.986650

In [156]:
print(wdi['iso_o'].nunique())
print(wdi['year'].nunique())

190
30

In [157]:
#at2010[at2010['GDP_pct'].isna()]

In [158]:
wdi.to_csv('../data/cleaned/attributes.csv', encoding='utf-8', index=False)